version: "3.9"

services:
  backend:
    build: .
    container_name: mws_backend_dev
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      APP_ENV=dev
      DB_HOST=host.docker.internal
      DB_PORT=5435
    volumes:
      - .:/app
    networks:
      - mwsnet

  postgres:
    image: postgres:16
    container_name: mws_postgres_dev
    env_file: .env
    ports:
      - "5435:5432"
    networks:
      - mwsnet
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

networks:
  mwsnet:

volumes:
  pgdata_dev:
