version: "3.9"

services:

  backend:
    build: .
    container_name: mws_backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - heuristic
      - ml
      - llm
    networks:
      - mwsnet

  postgres:
    image: postgres:16
    container_name: mws_postgres
    env_file: .env
    networks:
      - mwsnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  heuristic:
    image: teammate/heuristic-service:latest
    container_name: mws_heuristic
    expose:
      - "5000"
    networks:
      - mwsnet

  ml:
    image: teammate/ml-service:latest
    container_name: mws_ml
    expose:
      - "5000"
    networks:
      - mwsnet

  llm:
    image: sociologyml/security-findings-classifier:latest
    container_name: mws_llm
    env_file: .env
    expose:
      - "8000"
    networks:
      - mwsnet

networks:
  mwsnet:

volumes:
  pgdata:
